const { UpdateUtils, CreateAirdrop, AllAirdrops, SingleAirdrop, UpdateAirdrop, CategoryAirdrops, UpdateKyc, getDashboardInfos, getAllUserDetails, CreateUser, CreateBlog, UpdateBlog, AllBlogs, SingleBlog, FeatureBlogs, getCryptoBuysOrders, getCryptoSellsOrders, getSingleBuyOrder, getSingleSellOrder, closeAndConfirmBuyOrder, closeAndConfirmSellOrder, getGiftCardOrders, getSingleGiftCardOrder, creditGiftCustomer, UpdateProduct, SingleProduct, AllListedProducts, AllProductOrders, AllProducts, AllOpenAirdrops, AllRelatedBlogsExceptCurrent, CommentOnBlog, AllBlogComments, DeleteBlogImages, getAdminTransHistory, getBankWithdrawals, DeleteClosedAirdrop, getSingleWithdrawal } = require('../controllers/adminController')
const { AdminMiddleware } = require('../middleware/auth')

const router = require('express').Router()

router.put('/update-utils', AdminMiddleware, UpdateUtils)
router.post('/create-airdrop', AdminMiddleware, CreateAirdrop)
router.put('/update-airdrop', AdminMiddleware, UpdateAirdrop)
router.post('/delete-closed-airdrop', AdminMiddleware, DeleteClosedAirdrop)
router.get('/all-airdrops', AdminMiddleware, AllAirdrops)
router.get('/all-open-airdrops', AllOpenAirdrops)
router.get('/single-airdrop/:id', SingleAirdrop)
router.get('/category-airdrops/:category', CategoryAirdrops)
router.get('/all-products', AdminMiddleware, AllProducts)
router.put('/update-product', AdminMiddleware, UpdateProduct)
router.get('/listed-products', AllListedProducts)
router.get('/single-product/:id', SingleProduct)
router.get('/all-products-orders', AdminMiddleware, AllProductOrders)
router.get('/dashboard', AdminMiddleware, getDashboardInfos)
router.get('/get_users_details', AdminMiddleware, getAllUserDetails)
router.put('/update-kyc', AdminMiddleware, UpdateKyc)
router.post('/create-blog', AdminMiddleware, CreateBlog)
router.put('/update-blog', AdminMiddleware, UpdateBlog)
router.put('/delete_blog_img/:id', AdminMiddleware, DeleteBlogImages)
router.get('/all-blogs', AllBlogs)
router.get('/single-blog/:id', SingleBlog)
router.get('/feature-blogs/:feature', FeatureBlogs)
router.get('/related-blogs/:feature/:id', AllRelatedBlogsExceptCurrent)
router.post('/add-comment', CommentOnBlog)
router.get('/blog-comments/:id', AllBlogComments)
router.get('/get_buy_orders', getCryptoBuysOrders)
router.get('/get_sell_orders', getCryptoSellsOrders)
router.get('/get_single_buy/:id', getSingleBuyOrder)
router.get('/get_single_sell/:id', getSingleSellOrder)
router.post('/create_user', AdminMiddleware, CreateUser)
router.post('/confirm_buy/:id', AdminMiddleware, closeAndConfirmBuyOrder)
router.post('/confirm_sell/:id', AdminMiddleware, closeAndConfirmSellOrder)
router.get('/get_giftcard_orders', AdminMiddleware, getGiftCardOrders)
router.get('/get_single_giftcard_order/:id', AdminMiddleware, getSingleGiftCardOrder)
router.post('/credit_gift_customer/:id', AdminMiddleware, creditGiftCustomer)
router.get('/get_trans_history', AdminMiddleware, getAdminTransHistory)
router.get('/get_bank_withdrawals', AdminMiddleware, getBankWithdrawals)
router.get('/get_single_withdrawal/:id', AdminMiddleware, getSingleWithdrawal)


module.exports = router