module.exports = (sequelize, DataTypes) => {
    return sequelize.define('profit_tool', {
        user: { type: DataTypes.INTEGER },
        gen_id: { type: DataTypes.STRING },
        slug: { type: DataTypes.STRING },
        image: { type: DataTypes.STRING },
        title: { type: DataTypes.STRING },
        category: { type: DataTypes.JSON, defaultValue: [] },
        price: { type: DataTypes.FLOAT },
        about: { type: DataTypes.TEXT },
        feature1: { type: DataTypes.TEXT },
        feature2: { type: DataTypes.TEXT },
        bank_name: { type: DataTypes.STRING },
        account_number: { type: DataTypes.STRING },
        account_name: { type: DataTypes.STRING },
        video_link: { type: DataTypes.STRING },
        contact_detail: { type: DataTypes.STRING },
        status: { type: DataTypes.STRING, defaultValue: 'pending' },
        listing: { type: DataTypes.STRING, defaultValue: 'unlisted' },
        discount_percentage: { type: DataTypes.FLOAT, allowNull: true },
        discount_duration: { type: DataTypes.FLOAT, allowNull: true },
        discount_duration_type: { type: DataTypes.STRING, allowNull: true },
        total_ratings: { type: DataTypes.FLOAT, defaultValue: 0 },
        total_rate_persons: { type: DataTypes.FLOAT, defaultValue: 0 },
    })
}